Response handler
davkim1030/webserv pull request #18
Opened 2021-06-08 08:42 UTC by seohee-choi

- GET, HEAD, DELETE, TRACE, CONNECT, OPTION 메소드 입력에 대한 응답 처리
- 오류코드 (403, 404, 405, 500) 처리
- 오류코드에 따른 HTML파일 작성
- autoindex HTML파일 작성

#13

2021-06-08 10:32 UTC, davkim1030 requested changes
주로 주석과 코딩컨벤션적인 부분에 수정 사항이 있습니다
나머지는 괜찮은거 같습니다

2021-06-08 10:32 UTC, davkim1030 commented on includes/ResponseHandler.hpp
> +class ResponseHandler
어떤 역할을 하는 클래스인지 주석 달아주세요

2021-06-08 10:32 UTC, davkim1030 commented on includes/ResponseHandler.hpp
> +		Request _Req;
멤버 함수들에 대한 주석 작성해주세요

2021-06-08 10:32 UTC, davkim1030 commented on srcs/main.cpp
> +        /*
필요 없는 주석 삭제해주세요

2021-06-08 10:32 UTC, davkim1030 commented on includes/ResponseHandler.hpp
> +		void _makeTraceResponse(void);
언더바 지워주세욥

2021-06-08 10:32 UTC, davkim1030 commented on includes/ResponseHandler.hpp
> +		#define NOT_FOUND 404
상수 정의는 파일 맨 위에서 해주세요

2021-06-08 10:32 UTC, davkim1030 commented on includes/ResponseHandler.hpp
> +#endif
마지막 줄에 줄바꿈 추가해주세요

2021-06-08 10:32 UTC, davkim1030 commented on srcs/main.cpp
> +}
마지막 줄에 줄바꿈 추가해주세요

2021-06-08 10:55 UTC, skamo3 requested changes
확인 후 바꿔주세요
아니다 싶은 부분은 리뷰를 달아주세요

2021-06-08 10:55 UTC, skamo3 commented on includes/ResponseHandler.hpp
> +		#define HEAD_METHOD 3
이 줄 위로 되어있는 define 변수들 모두 13line으로 올려주세요
상수는 private으로 있는것보단 전역으로 나와있는게 훨씬 좋다고 생각합니다

2021-06-08 10:55 UTC, skamo3 commented on srcs/main.cpp
> +		//엔드는 마지막걸 가리키는게아니라 마지막의 다음걸 가리키는거임!!!!!!!!!!!!! 쓰지마셈!!!!!!!!!!!1
의미없는 주석은 지워주세요

2021-06-08 10:55 UTC, skamo3 commented on includes/ResponseHandler.hpp
> +		void _throwErrorResponse(int httpStatus, std::string version) throw(Response);
위에서는 void int 처럼 자료형만 넣었는데 여기서는 자료형과 변수명을 다 써주셨네요
하나로 통일해서 써주세요!

2021-06-08 10:55 UTC, skamo3 commented on srcs/ResponseHandler.cpp
> +:_Req(src._Req), _mimeType(src._mimeType) {};
다른 멤버변수들은 복사하지 않아도 괜찮은건가요?

2021-06-08 10:55 UTC, skamo3 commented on srcs/ResponseHandler.cpp
> +
> 다른 멤버변수들은 복사하지 않아도 괜찮은건가요?

복사연산자도 위와 같습니다

2021-06-08 10:55 UTC, skamo3 commented on srcs/main.cpp
> +		Request Req(buffer);
변수명 코딩컨벤션 지켜서
Request request(buffer); 
와 같은 방식으로 선언하는게 어떨까 합니다

2021-06-08 10:55 UTC, skamo3 commented on srcs/main.cpp
> +		ResponseHandler ReqHan(Req, --server.end());
ResponsHandler 인데 Req로 붙어있어요

2021-06-08 10:55 UTC, skamo3 commented on srcs/main.cpp
> +		Response Res = ReqHan.makeResponse();
> 변수명 코딩컨벤션 지켜서
Request request(buffer);
와 같은 방식으로 선언하는게 어떨까 합니다  

위와 동일한 이슈입니다

2021-06-08 16:55 UTC, seohee-choi commented on srcs/ResponseHandler.cpp
> +:_Req(src._Req), _mimeType(src._mimeType) {};
HTTP 요청과 응답은 유지되지 않으므로 (복사되어서도 안되므로) 다른 멤버변수들을 복사할 필요가 없다고 생각했습니다. 
복사생성자 자체를 삭제하는 쪽으로 하고 싶은데 문제가 없을까요?

2021-06-09 03:02 UTC, davkim1030 approved these changes
LGTM

2021-06-09 05:30 UTC, skamo3 approved these changes
전보다 더 깔끔하게 바뀌었네요! 고생하셨습니다

2021-06-09 05:46 UTC, merged