Request의 uri를 rawUri로 수정, uri에서 directory 파싱
davkim1030/webserv pull request #20
Opened 2021-06-09 16:39 UTC by seohee-choi

- uri 변수를 rawUri로 수정
- rawUri를 /기준으로 파싱해 directory 변수에 저장하는 parseDirectory 함수 추가
- location 검색을 rawUri가 아닌 directory에서 진행
#19

2021-06-10 06:13 UTC, skamo3 approved these changes
고생하셨습니다

2021-06-10 06:16 UTC, davkim1030 approved these changes
수고하셨습니다

2021-06-10 06:20 UTC, skamo3 requested changes
확인요망

2021-06-10 06:20 UTC, skamo3 commented on srcs/Request.cpp
> +* 가공되지 않은 요청 문자열을 가져와 method, rawUri, httpVersion, header, body를 파싱합니다.
"가공되지 않은 HTTP 요청 문자열"   이라고 쓰면 좀 더 가독성이 올라갈 것 같습니다

2021-06-10 15:46 UTC, seohee-choi commented
**요청 uri 파싱 방식 변경**
- 원본 요청 uri : rawUri 변수 (이 변수로 cgi 파악)
- 원본 요청 uri에서 쿼리스트링/가상경로를 제외한 uri : uri 변수 (이 변수로 이 경로가 파일인지 디렉토리인지 파악)
- 원본 요청 uri에서 파일명/쿼리스트링/가상경로를 제외한 uri : directory 변수 (이 변수로 config file의 location 파악)

2021-06-11 04:37 UTC, skamo3 approved these changes
따로 건들 부분이 없네요  고생하셨습니다

2021-06-11 04:37 UTC, merged