404 Response 반환시 무한 대기하는 문제 수정
davkim1030/webserv pull request #22
Opened 2021-06-11 15:04 UTC by seohee-choi

- 에러 Response 반환시 content-length, content-type 헤더 추가
#21

2021-06-11 17:04 UTC, davkim1030 requested changes
![image](https://user-images.githubusercontent.com/7599727/121722319-43187380-cb20-11eb-816f-4a6c607c910c.png)
- 있는 파일 읽어서 Response Body 만들 때 마지막 줄이 안 나오는 이슈가 있습니다. `ResponseHandler.cpp` 248번째 줄에 있는 `get_next_line` 호출 안 하시면 해결 됩니다.

![image](https://user-images.githubusercontent.com/7599727/121724209-8247c400-cb22-11eb-98ff-90d2a354e55d.png)
- 그리고 `contentTypeHeader`가 빈 값으로 오는 이슈가 있는데, `ResponseHandler.cpp` 251번째 줄에 `addContentTypeHeader`에 `resourcePath`를 넣는건  못 된거 같아요. 그런데 이 부분 수정해도 안 되더라고요. -> **수정 부탁드립니다**

2021-06-11 18:10 UTC, davkim1030 requested changes
코멘트 단 부분들 처리 부탁드립니다

2021-06-11 18:10 UTC, davkim1030 commented on srcs/ResponseHandler.cpp
>  	get_next_line(fd, &buffer);
있는 파일 읽어서 Response Body 만들 때 마지막 줄이 안 나오는 이슈가 있습니다.
정상 동작을 위해서 이 줄 삭제해주세요

2021-06-11 18:10 UTC, davkim1030 commented on srcs/ResponseHandler.cpp
>  	addContentTypeHeader(resourcePath);
이 부분은 `resourcePath` 그대로 넣으면 알맞은 `Content-Type`이 안 들어갈 것으로 보입니다.
- Query String 처리하고
- 확장자만 뽑아서
넘겨주면 될 것 같습니다.

2021-06-11 18:10 UTC, davkim1030 commented on srcs/ResponseHeader.cpp
> +		addResponseHeader("Content-Type", mimeType["text/plain"]);
`addResponseHeader("Content-Type", "text/plain");`
으로 수정하셔야 정상 작동합니다.

2021-06-11 18:12 UTC, seohee-choi commented
확인했습니다 금일중으로 처리하겠습니다

2021-06-12 18:28 UTC, seohee-choi commented
1.  content-type 헤더 함수의 오류를 수정했습니다. 
2. 이제 GET 메소드에서 content-type 헤더를 추가할 때는 파일명의 확장자를 기준으로 찾습니다.
3. GET 메소드에서 파일을 불러올 때 파일의 마지막줄이 잘려 오는 오류를 수정했습니다.
3. HTML을 읽고 생성할 때 모든 줄 마지막에 개행을 추가했습니다.
4. 입력받은 URI 경로 그대로 접근할 경우 파일을 찾지 못하는 문제가 있어, 모든 경로 맨 앞부분에 ~~.~~을 추가해주었습니다.
- 그러자 content-location 헤더를 추가해주는 부분에서 맨 앞에 ~~.~~이 달려서 나와 모든 경로 맨 앞부분 한글자를 지우고 헤더로 추가해주게 되었습니다. 이 부분이 무엇인가 잘못되었다는 느낌이 강하게 드는데 일단 올려둡니다.

2021-06-13 06:27 UTC, davkim1030 requested changes
부탁해요~

2021-06-13 06:27 UTC, davkim1030 commented on test/test.html
> +</html>
줄바꿈~~~~ 추가해주세요

2021-06-13 06:27 UTC, davkim1030 commented on index.html
> +</html>
`'\n'` 넣어주세요

2021-06-13 06:48 UTC, davkim1030 approved these changes
LGTM 수고하셨습니다

2021-06-13 08:43 UTC, seohee-choi commented
- directory 파싱 방식 재수정  (경로 여러개들어와도 처리되게함) #19 
- put bug fix #25

2021-06-13 08:46 UTC, seohee-choi commented
close #19 #25

2021-06-13 09:14 UTC, davkim1030 approved these changes
LGTM 👍 
![](https://user-images.githubusercontent.com/7599727/121800878-3a828300-cc6f-11eb-8f8a-8100a0ddba8d.png)

2021-06-13 09:15 UTC, skamo3 approved these changes
good!

2021-06-13 09:17 UTC, merged

2021-06-13 09:20 UTC, seohee-choi commented
close #19